<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="JoshnaRajput" failures="1" tests="9" name="com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest" time="115.104" errors="0" timestamp="2025-03-26T12:07:54 IST" skipped="0">
  <testcase classname="com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest" name="doLoginTest" time="0.797"/>
  <testcase classname="com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest" name="doNavigateToSelectHospitalLocationTest" time="0.005"/>
  <testcase classname="com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest" name="doNavigateToHISHomeTest" time="9.489"/>
  <testcase classname="com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest" name="doNavigateToOrderPacksTest" time="1.942"/>
  <testcase classname="com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest" name="CLM_Order_Packs_TC_02" time="29.641"/>
  <testcase classname="com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest" name="CLM_Order_Packs_TC_03" time="32.993"/>
  <testcase classname="com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest" name="CLM_Order_Packs_TC_06" time="37.415">
    <failure message="the status of diagnosis after ticking on covid19 is not matching, it should reflect deleted expected [Deleted] but found [New]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: the status of diagnosis after ticking on covid19 is not matching, it should reflect deleted expected [Deleted] but found [New]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest.CLM_Order_Packs_TC_06(OrderPacksTest.java:312)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- CLM_Order_Packs_TC_06 -->
  <testcase classname="com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest" name="CLM_Order_Packs_TC_04" time="1.751"/>
  <testcase classname="com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest" name="CLM_Order_Packs_TC_07" time="1.071"/>
</testsuite> <!-- com.qa.HIS.BrowserCompatibility_HIS.OrderPacksTest -->
